# Generated by Django 3.0.7 on 2020-06-19 03:28

import django.core.validators
from django.db import migrations, models
import djbver.apps.sms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='올바른 번호가 아닙니다', regex='^010[-\\s]??\\d{3,4}[-\\s]??\\d{4}$')], verbose_name='전화번호')),
                ('message', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('reserved', 'Reserved'), ('scheduled', 'Scheduled'), ('fail', 'Fail')], max_length=20, null=True, verbose_name='상태')),
            ],
            options={
                'verbose_name': 'SMS 이력',
                'verbose_name_plural': 'SMS 이력들',
                'db_table': 'sms_histories',
            },
        ),
        migrations.CreateModel(
            name='SmsVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='올바른 번호가 아닙니다', regex='^010[-\\s]??\\d{3,4}[-\\s]??\\d{4}$')], verbose_name='전화번호')),
                ('code', models.CharField(max_length=10, verbose_name='인증코드')),
                ('expire', models.DateTimeField(default=djbver.apps.sms.models.minutes_hence, verbose_name='만료일')),
            ],
            options={
                'verbose_name': 'SMS 인증코드',
                'verbose_name_plural': 'SMS 인증코드들',
                'db_table': 'sms_verify_codes',
                'unique_together': {('phone', 'code')},
            },
        ),
    ]
